### ISSUE TITLE
Contract List Page changes

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#111]
- Go from unassigned/assigned to In Progress/Upcoming/All
- Add a "start work" button to actions dropdown.
- Drop controller number.

(Below added 8/3 from below comments from @shellicious for tracking)
#### Definite changes:
- [x] The action for updating a contract should be called "Update contract" instead of "View progress"
- [x] Expose item number
- [x] Remove star column
- [x] Add "days in current step" column
- [x] As mentioned above, 2 lists for contracts. One is "in progress" (contracts moving through the renew / extend / bidding process) and one is "all contracts" (ordered by expiration by default)
#### Open questions / potential changes:
- [x] Use red / yellow to denote "in progress" contracts that are stuck in steps for more than 14 / 7 days (not sure about the exact lengths of time we should use)
- [x]  Use red / yellow to denote contracts that are expiring soon (red = within 60 days, yellow = within 60-120 days). Also not sure about the lengths of time, or how customizable it should be.
- [ ] A separate tab or list of "dead" contracts: contracts that have expired and are no longer in use. This applies both to contracts which expired and were not renewed/extended/bid, or contracts which expired and were successfully bid out.

**Comment by bsmithgall** [comment]
![screen shot 2015-07-14 at 1 14 32 am](https://cloud.githubusercontent.com/assets/1957344/8666893/b6252f60-29c5-11e5-80a5-bf9f36713f88.png)

Upcoming filter is expiration date <= today + 90 days. This is actually most contracts though, so maybe we want to drop that to 60 days.

**Comment by bsmithgall** [comment]
Now with more last activity
![screen shot 2015-07-14 at 1 30 28 am](https://cloud.githubusercontent.com/assets/1957344/8667053/f4cc9d6e-29c7-11e5-8d01-398073462490.png)

**Comment by bsmithgall** [comment]
Ed wanted to merge the upcoming/all sections and keep them sorted by expiration date. This seems to make sense. He also wants to nuke the "starred" option, which is probably fine because I'm not sure how often it gets used. An open question for me though is what to do about already-expired contracts? I suppose many of them won't be in the "Upcoming" queue and will instead be "in progress."

A few additional open questions:
- How do we handle "process forking" (i.e. you are part-way through the process and you get a renewal)?
- How do we handle the fact that metadata about a contract gets assigned as the contract goes along? How do we make that configurable in the future without hard-coding it? I don't have any good ideas right now.
- I think unifying all of the possible actions into one tab is the right way to move forward based on what Ed/Riley said.

**Comment by msknee** [comment]
From testing with @rileystewart, Ed, and Slim this week (7/13-7/17):

#### Definite changes:
- [ ] The action for updating a contract should be called "Update contract" instead of "View progress"
- [ ] Expose item number
- [ ] Remove star column
- [ ] Add "days in current step" column
- [ ] As mentioned above, 2 lists for contracts. One is "in progress" (contracts moving through the renew / extend / bidding process) and one is "all contracts" (ordered by expiration by default)

#### Open questions / potential changes:
- [ ] Use red / yellow to denote "in progress" contracts that are stuck in steps for more than 14 / 7 days (not sure about the exact lengths of time we should use)
- [x]  Use red / yellow to denote contracts that are expiring soon (red = within 60 days, yellow = within 60-120 days). Also not sure about the lengths of time, or how customizable it should be.
- [ ] A separate tab or list of "dead" contracts: contracts that have expired and are no longer in use. This applies both to contracts which expired and were not renewed/extended/bid, or contracts which expired and were successfully bid out.

**Comment by bsmithgall** [comment]
For item number, we are just exposing the internal contract id right? Should the column be called `Item #`? (`id` is much shorter to save those sweet, sweet horizontal pixels)

**Comment by bsmithgall** [comment]
![screen shot 2015-08-03 at 2 00 17 pm](https://cloud.githubusercontent.com/assets/1957344/9047684/561bd636-39e8-11e5-8206-fa5177736c99.png)

**Comment by bsmithgall** [comment]
Re: "A separate tab/view for dead contracts" -- I'm going to open a new issue for that.
