### ISSUE TITLE
County number

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#332]
I hesitate to do this, but we seem to be getting enough pushback re county controller number that I'm starting to think we should just add it. No idea how difficult this will be.

**Comment by msknee** [comment]
update: we are meeting with Dir. Ashbaugh sometime this week (@rileystewart is setting up the meeting) to discuss whether or not to incorporate this. Also chatting with Bonnie from DPW to learn more about their internal process today.

**Comment by rileystewart** [comment]
director said he didn't want to meet about it.  they need to give us a
reasonable business explanation as to why that needs added as opposed to
them changing something.  the whole point of scout is to simplify things
for ppl and adding numbers that they've used just because for years doesn't
make sense.  They should be using city controller number on forms since
that is now easy to find in scout

**Comment by hamhands** [comment]
Riley is reaching out to DPW to ask them to explain their case for including the county number and discuss maintaining the data.

**Comment by bsmithgall** [comment]
This is mostly a data issue, and is totally doable within the current featureset
