### ISSUE TITLE
Beacon admin submission end time is not working

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#561]
I was trying to adjust the depository services RFP via admin.  I extended it and put the time that submissions were due at 15:45 (aka 3:45pm)

When I go back to beacon it changes it to 10:45am.  The only way I could get it to work correctly was by doing it by clicking 'edit this opportunity' from the opportunity in beacon.  Then it changed.

**Comment by bsmithgall** [comment]
Did you put 15.45 or did you put 3.45 pm?

**Comment by rileystewart** [comment]
there are no am/pm options. just hours 1-24

**Comment by bsmithgall** [comment]
Where are you trying to do this from? I have AM/PM:

![screen shot 2015-10-29 at 9 15 03 am](https://cloud.githubusercontent.com/assets/1957344/10824440/993e2d78-7e1d-11e5-93d4-43c8bc6c6c81.png)

**Comment by rileystewart** [comment]
that is if you are editing it from the post.  This problem is from the
Admin section.  If you go to Admin:Beacon:Opportunities and click to edit
it, the time is not working.  Sorry if I didn't put that it wasn't working
VIA ADMIN in my original message, I thought I had clarified that. my bad.

**Comment by bsmithgall** [comment]
Ah! That is likely due to the way that timezones are handled. I don't think they are handled at all in the admin. I'll work on it, but I would highly recommend using the Beacon form instead -- the Admin doesn't allow to pick categories and do other things that are critical to Beacon.

I'm actually going to lock down the creation of new opportunities from the Admin. Please use Beacon directly instead.
