### ISSUE TITLE
conductor/scout mismatch

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#584]
MAINTENANCE & REPAIR: NEDERMAN EXHAUST SYST shows up as a current contract in scout that is being worked on.

It is not showing up if I search in admin as a contract that is being worked on.  If i click on 'action:view in scout' though it shows up.

**Comment by bsmithgall** [comment]
What's the expected behavior here? It shouldn't show up in the Scout Admin because it isn't completed (it's currently in progress in Conductor, see #499)

It doesn't show up in search results, so people won't be able to find it unless they have the exact URL, which should make it ok.

![screen shot 2015-11-04 at 10 34 17 am](https://cloud.githubusercontent.com/assets/1957344/10942826/b10268c2-82df-11e5-8537-a7496897a749.png)

**Comment by rileystewart** [comment]
it should show up in Admin if I search contracts.  I was told that whenever one was 'started' it showed up in admin w/ no blank information until completed

**Comment by bsmithgall** [comment]
In-progress contracts show up in the Conductor / Contract section of the admin:

![screen shot 2015-11-04 at 10 39 44 am](https://cloud.githubusercontent.com/assets/1957344/10942986/6810865c-82e0-11e5-8642-e200c8a2a20e.png)
