### ISSUE TITLE
Flow changes

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#82]
From @shellicious's google doc: 
- [ ] After clicking “professional services” and no to “emergency” and no to “sole source”, we need a question page with 3 $ ranges: 0-24,999, 25-29,999, and 30,000+.
- [x] /buy-something: “I don’t know” should open Scout in a new tab
- [ ] Remove /multiple-purchases questions because it doesn’t change the answer, “phone quote”

**Comment by hamhands** [comment]
@shellicious are you sure about removing multiple purchases? How would the user get to [b-bids](https://pittsburgh-purchasing.herokuapp.com/sherpa/b-bid)?

**Comment by hamhands** [comment]
Also do we really want to do a new tab for the scout redirect? Also not really sure how to do a target=_blank with flask. Thoughts @bsmithgall?

**Comment by hamhands** [comment]
Also we need to clarify whether there really are 3 thresholds for non-sole-sourced services. Do phone quotes cover services too? @bsmithgall and I were talking about this yesterday and I'm not sure we have a definitive answer.

**Comment by bsmithgall** [comment]
@hamhands why can't you just put the `target=_blank` directly in the relevant template's `a` tag?

**Comment by hamhands** [comment]
@bsmithgall wouldn't that make all buttons open in new tabs?

**Comment by bsmithgall** [comment]
True, you could add a flag for it -- `new_tab` or something.

**Comment by hamhands** [comment]
Ah that's a thought

**Comment by msknee** [comment]
Additional flow changes after meetings with Law and OMB:
- [ ] /use-it: Include a link to Scout on this page too. @rileystewart made the great point that someone may want to look up the controller # or expiration date of a contract, in order to make the purchase.
- [ ] Single use v multiple use _does_ matter. Multiple use of a service or commodity that costs between $10-30k over time actually needs to be an A bid.

**Comment by hamhands** [comment]
Wontfix this @bsmithgall @shellicious?
